static const IntStrPair IPPROTO_IP_OPTIONS[] = {
#ifdef IP_TOS
    ADD(IP_TOS),
#endif
#ifdef IP_TTL
    ADD(IP_TTL),
#endif
#ifdef IP_HDRINCL
    ADD(IP_HDRINCL),
#endif
#ifdef IP_OPTIONS
    ADD(IP_OPTIONS),
#endif
#ifdef IP_ROUTER_ALERT
    ADD(IP_ROUTER_ALERT),
#endif
#ifdef IP_RECVOPTS
    ADD(IP_RECVOPTS),
#endif
#ifdef IP_RETOPTS
    ADD(IP_RETOPTS),
#endif
#ifdef IP_PKTINFO
    ADD(IP_PKTINFO),
#endif
#ifdef IP_PKTOPTIONS
    ADD(IP_PKTOPTIONS),
#endif
#ifdef IP_MTU_DISCOVER
    ADD(IP_MTU_DISCOVER),
#endif
#ifdef IP_RECVERR
    ADD(IP_RECVERR),
#endif
#ifdef IP_RECVTTL
    ADD(IP_RECVTTL),
#endif
#ifdef IP_RECVTOS
    ADD(IP_RECVTOS),
#endif
#ifdef IP_MTU
    ADD(IP_MTU),
#endif
#ifdef IP_FREEBIND
    ADD(IP_FREEBIND),
#endif
#ifdef IP_IPSEC_POLICY
    ADD(IP_IPSEC_POLICY),
#endif
#ifdef IP_XFRM_POLICY
    ADD(IP_XFRM_POLICY),
#endif
#ifdef IP_PASSSEC
    ADD(IP_PASSSEC),
#endif
#ifdef IP_TRANSPARENT
    ADD(IP_TRANSPARENT),
#endif
#ifdef IP_RECVRETOPTS
    ADD(IP_RECVRETOPTS),
#endif
#ifdef IP_ORIGDSTADDR
    ADD(IP_ORIGDSTADDR),
#endif
#ifdef IP_RECVORIGDSTADDR
    ADD(IP_RECVORIGDSTADDR),
#endif
#ifdef IP_MINTTL
    ADD(IP_MINTTL),
#endif
#ifdef IP_NODEFRAG
    ADD(IP_NODEFRAG),
#endif
#ifdef IP_MULTICAST_IF
    ADD(IP_MULTICAST_IF),
#endif
#ifdef IP_MULTICAST_TTL
    ADD(IP_MULTICAST_TTL),
#endif
#ifdef IP_MULTICAST_LOOP
    ADD(IP_MULTICAST_LOOP),
#endif
#ifdef IP_ADD_MEMBERSHIP
    ADD(IP_ADD_MEMBERSHIP),
#endif
#ifdef IP_DROP_MEMBERSHIP
    ADD(IP_DROP_MEMBERSHIP),
#endif
#ifdef IP_UNBLOCK_SOURCE
    ADD(IP_UNBLOCK_SOURCE),
#endif
#ifdef IP_BLOCK_SOURCE
    ADD(IP_BLOCK_SOURCE),
#endif
#ifdef IP_ADD_SOURCE_MEMBERSHIP
    ADD(IP_ADD_SOURCE_MEMBERSHIP),
#endif
#ifdef IP_DROP_SOURCE_MEMBERSHIP
    ADD(IP_DROP_SOURCE_MEMBERSHIP),
#endif
#ifdef IP_MSFILTER
    ADD(IP_MSFILTER),
#endif
#ifdef MCAST_JOIN_GROUP
    ADD(MCAST_JOIN_GROUP),
#endif
#ifdef MCAST_BLOCK_SOURCE
    ADD(MCAST_BLOCK_SOURCE),
#endif
#ifdef MCAST_UNBLOCK_SOURCE
    ADD(MCAST_UNBLOCK_SOURCE),
#endif
#ifdef MCAST_LEAVE_GROUP
    ADD(MCAST_LEAVE_GROUP),
#endif
#ifdef MCAST_JOIN_SOURCE_GROUP
    ADD(MCAST_JOIN_SOURCE_GROUP),
#endif
#ifdef MCAST_LEAVE_SOURCE_GROUP
    ADD(MCAST_LEAVE_SOURCE_GROUP),
#endif
#ifdef MCAST_MSFILTER
    ADD(MCAST_MSFILTER),
#endif
#ifdef IP_MULTICAST_ALL
    ADD(IP_MULTICAST_ALL),
#endif
#ifdef IP_UNICAST_IF
    ADD(IP_UNICAST_IF)
#endif
};
