static const IntStrPair SOL_IPV6_OPTIONS[] = {
#ifdef IPV6_ADDRFORM
    ADD(IPV6_ADDRFORM),
#endif
#ifdef IPV6_2292PKTINFO
    ADD(IPV6_2292PKTINFO),
#endif
#ifdef IPV6_2292HOPOPTS
    ADD(IPV6_2292HOPOPTS),
#endif
#ifdef IPV6_2292DSTOPTS
    ADD(IPV6_2292DSTOPTS),
#endif
#ifdef IPV6_2292RTHDR
    ADD(IPV6_2292RTHDR),
#endif
#ifdef IPV6_2292PKTOPTIONS
    ADD(IPV6_2292PKTOPTIONS),
#endif
#ifdef IPV6_CHECKSUM
    ADD(IPV6_CHECKSUM),
#endif
#ifdef IPV6_HOPLIMIT
    ADD(IPV6_HOPLIMIT),
#endif
#ifdef IPV6_NEXTHOP
    ADD(IPV6_NEXTHOP),
#endif
#ifdef IPV6_AUTHHDR
    ADD(IPV6_AUTHHDR),
#endif
#ifdef IPV6_FLOWINFO
    ADD(IPV6_FLOWINFO),
#endif
#ifdef IPV6_UNICAST_HOPS
    ADD(IPV6_UNICAST_HOPS),
#endif
#ifdef IPV6_MULTICAST_IF
    ADD(IPV6_MULTICAST_IF),
#endif
#ifdef IPV6_MULTICAST_HOPS
    ADD(IPV6_MULTICAST_HOPS),
#endif
#ifdef IPV6_MULTICAST_LOOP
    ADD(IPV6_MULTICAST_LOOP),
#endif
#ifdef IPV6_ADD_MEMBERSHIP
    ADD(IPV6_ADD_MEMBERSHIP),
#endif
#ifdef IPV6_DROP_MEMBERSHIP
    ADD(IPV6_DROP_MEMBERSHIP),
#endif
#ifdef IPV6_ROUTER_ALERT
    ADD(IPV6_ROUTER_ALERT),
#endif
#ifdef IPV6_MTU_DISCOVER
    ADD(IPV6_MTU_DISCOVER),
#endif
#ifdef IPV6_MTU
    ADD(IPV6_MTU),
#endif
#ifdef IPV6_RECVERR
    ADD(IPV6_RECVERR),
#endif
#ifdef IPV6_V6ONLY
    ADD(IPV6_V6ONLY),
#endif
#ifdef IPV6_JOIN_ANYCAST
    ADD(IPV6_JOIN_ANYCAST),
#endif
#ifdef IPV6_LEAVE_ANYCAST
    ADD(IPV6_LEAVE_ANYCAST),
#endif
#ifdef IPV6_FLOWLABEL_MGR
    ADD(IPV6_FLOWLABEL_MGR),
#endif
#ifdef IPV6_FLOWINFO_SEND
    ADD(IPV6_FLOWINFO_SEND),
#endif
#ifdef IPV6_IPSEC_POLICY
    ADD(IPV6_IPSEC_POLICY),
#endif
#ifdef IPV6_XFRM_POLICY
    ADD(IPV6_XFRM_POLICY),
#endif
#ifdef IPV6_RECVPKTINFO
    ADD(IPV6_RECVPKTINFO),
#endif
#ifdef IPV6_PKTINFO
    ADD(IPV6_PKTINFO),
#endif
#ifdef IPV6_RECVHOPLIMIT
    ADD(IPV6_RECVHOPLIMIT),
#endif
#ifdef IPV6_HOPLIMIT
    ADD(IPV6_HOPLIMIT),
#endif
#ifdef IPV6_RECVHOPOPTS
    ADD(IPV6_RECVHOPOPTS),
#endif
#ifdef IPV6_HOPOPTS
    ADD(IPV6_HOPOPTS),
#endif
#ifdef IPV6_RTHDRDSTOPTS
    ADD(IPV6_RTHDRDSTOPTS),
#endif
#ifdef IPV6_RECVRTHDR
    ADD(IPV6_RECVRTHDR),
#endif
#ifdef IPV6_RTHDR
    ADD(IPV6_RTHDR),
#endif
#ifdef IPV6_RECVDSTOPTS
    ADD(IPV6_RECVDSTOPTS),
#endif
#ifdef IPV6_DSTOPTS
    ADD(IPV6_DSTOPTS),
#endif
#ifdef IPV6_RECVPATHMTU
    ADD(IPV6_RECVPATHMTU),
#endif
#ifdef IPV6_PATHMTU
    ADD(IPV6_PATHMTU),
#endif
#ifdef IPV6_DONTFRAG
    ADD(IPV6_DONTFRAG),
#endif
#ifdef IPV6_RECVTCLASS
    ADD(IPV6_RECVTCLASS),
#endif
#ifdef IPV6_TCLASS
    ADD(IPV6_TCLASS),
#endif
#ifdef IPV6_ADDR_PREFERENCES
    ADD(IPV6_ADDR_PREFERENCES),
#endif
#ifdef IPV6_MINHOPCOUNT
    ADD(IPV6_MINHOPCOUNT),
#endif
#ifdef IPV6_ORIGDSTADDR
    ADD(IPV6_ORIGDSTADDR),
#endif
#ifdef IPV6_TRANSPARENT
    ADD(IPV6_TRANSPARENT),
#endif
#ifdef IPV6_UNICAST_IF
    ADD(IPV6_UNICAST_IF)
#endif
};
