#define _GNU_SOURCE

#ifndef CONSTANT_STRING_H
#define CONSTANT_STRING_H

#include <arpa/inet.h>
#include <asm-generic/ioctls.h>
#include <fcntl.h>
#include <linux/ax25.h>
#include <linux/if_eql.h>
#include <linux/if_plip.h>
#include <linux/if_ppp.h>
#include <linux/ipx.h>
#include <linux/mroute.h>
#include <linux/sockios.h>
#include <linux/wireless.h>
#include <netinet/tcp.h>
#include <sys/socket.h>
#include <unistd.h>

#define MEMBER_SIZE(type, member) sizeof(((type *)0)->member)

typedef struct {
	int cons;
	const char str[30];
} IntStrPair;

char *alloc_string_from_cons(int cons, const IntStrPair *map, int map_size);

char *alloc_sock_domain_str(int domain);
char *alloc_sock_type_str(int type);
char *alloc_sock_optname_str(int optname);
char *alloc_fcntl_cmd_str(int cmd);
char *alloc_ioctl_request_str(int request);

static const IntStrPair SOCKET_DOMAINS[] = {
    {AF_UNIX, "AF_UNIX"}, {AF_INET, "AF_INET"},       {AF_INET6, "AF_INET6"},
    {AF_IPX, "AF_IPX"},   {AF_NETLINK, "AF_NETLINK"}, {AF_PACKET, "AF_PACKET"}};

static const IntStrPair SOCKET_TYPES[] = {{SOCK_STREAM, "SOCK_STREAM"},
					  {SOCK_DGRAM, "SOCK_DGRAM"},
					  {SOCK_SEQPACKET, "SOCK_SEQPACKET"},
					  {SOCK_RAW, "SOCK_RAW"},
					  {SOCK_RDM, "SOCK_RDM"},
					  {SOCK_PACKET, "SOCK_PACKET"}};

static const IntStrPair SOCKET_OPTIONS[] = {
    // Socket-level options (asm-generic/socket.h)
    {SO_DEBUG, "SO_DEBUG"},
    {SO_BROADCAST, "SO_BROADCAST"},
    {SO_REUSEADDR, "SO_REUSEADDR"},
    {SO_KEEPALIVE, "SO_KEEPALIVE"},
    {SO_LINGER, "SO_KEEPALIVE"},
    {SO_OOBINLINE, "SO_OOBINLINE"},
    {SO_SNDBUF, "SO_SNDBUF"},
    {SO_RCVBUF, "SO_RCVBUF"},
    {SO_DONTROUTE, "SO_DONTROUTE"},
    {SO_RCVLOWAT, "SO_RCVLOWAT"},
    {SO_RCVTIMEO, "SO_RCVTIMEO"},
    {SO_SNDLOWAT, "SO_SNDLOWAT"},
    {SO_SNDTIMEO, "SO_SNDTIMEO"},
    // IP-level options (linux/in.h) Wrong place?
    {IP_TOS, "IP_TOS"},
    {IP_TTL, "IP_TTL"},
    {IP_HDRINCL, "IP_HDRINCL"},
    {IP_OPTIONS, "IP_OPTIONS"},
    {IP_ROUTER_ALERT, "IP_ROUTER_ALERT"},
    {IP_RECVOPTS, "IP_RECVOPTS"},
    {IP_RETOPTS, "IP_RETOPTS"},
    {IP_PKTINFO, "IP_PKTINFO"},
    {IP_PKTOPTIONS, "IP_PKTOPTIONS"},
    {IP_MTU_DISCOVER, "IP_MTU_DISCOVER"},
    {IP_RECVERR, "IP_RECVERR"},
    {IP_RECVTTL, "IP_RECVTTL"},
    {IP_RECVTOS, "IP_RECVTOS"},
    {IP_MTU, "IP_MTU"},
    {IP_FREEBIND, "IP_FREEBIND"},
    {IP_IPSEC_POLICY, "IP_IPSEC_POLICY"},
    {IP_XFRM_POLICY, "IP_XFRM_POLICY"},
    {IP_PASSSEC, "IP_PASSSEC"},
#if !defined(__ANDROID__) || __ANDROID_API__ >= 21
    {IP_TRANSPARENT, "IP_TRANSPARENT"},
#endif
    // TCP-level options (netinet/tcp.h)
    {TCP_NODELAY, "TCP_NODELAY"},
    {TCP_MAXSEG, "TCP_MAXSEG"},
    {TCP_CORK, "TCP_CORK"},
    {TCP_KEEPIDLE, "TCP_KEEPIDLE"},
    {TCP_KEEPINTVL, "TCP_KEEPINTVL"},
    {TCP_KEEPCNT, "TCP_KEEPCNT"},
    {TCP_SYNCNT, "TCP_SYNCNT"},
    {TCP_LINGER2, "TCP_LINGER2"},
    {TCP_DEFER_ACCEPT, "TCP_DEFER_ACCEPT"},
    {TCP_WINDOW_CLAMP, "TCP_WINDOW_CLAMP"},
    {TCP_INFO, "TCP_INFO"},
    {TCP_QUICKACK, "TCP_QUICKACK"},
    {TCP_CONGESTION, "TCP_CONGESTION"},
#if !defined(__ANDROID__) || __ANDROID_API__ >= 21
    {TCP_MD5SIG, "TCP_MD5SIG"},
    {TCP_THIN_LINEAR_TIMEOUTS, "TCP_THIN_LINEAR_TIMEOUTS"},
    {TCP_THIN_DUPACK, "TCP_THIN_DUPACK"},
    {TCP_USER_TIMEOUT, "TCP_USER_TIMEOUT"},
    {TCP_REPAIR, "TCP_REPAIR"},
    {TCP_REPAIR_QUEUE, "TCP_REPAIR_QUEUE"},
    {TCP_QUEUE_SEQ, "TCP_QUEUE_SEQ"},
    {TCP_REPAIR_OPTIONS, "TCP_REPAIR_OPTIONS"},
    {TCP_FASTOPEN, "TCP_FASTOPEN"},
    {TCP_TIMESTAMP, "TCP_TIMESTAMP"}
#endif
};

static const IntStrPair FCNTL_CMDS[] = {
    {F_GETFD, "F_GETFD"},	   {F_GETFL, "F_GETFL"},
    {F_GETOWN, "F_GETOWN"},	 {F_GETSIG, "F_GETSIG"},
    {F_GETLEASE, "F_GETLEASE"},     {F_GETPIPE_SZ, "F_GETPIPE_SZ"},
    {F_DUPFD, "F_DUPFD"},	   {F_DUPFD_CLOEXEC, "F_DUPFD_CLOEXEC"},
    {F_SETFD, "F_SETFD"},	   {F_SETFL, "F_SETFL"},
    {F_SETOWN, "F_SETOWN"},	 {F_SETSIG, "F_SETSIG"},
    {F_SETLEASE, "F_SETLEASE"},     {F_NOTIFY, "F_NOTIFY"},
    {F_SETPIPE_SZ, "F_SETPIPE_SZ"}, {F_SETLK, "F_SETLK"},
    {F_SETLKW, "F_SETLKW"},	 {F_GETLK, "F_GETLK"},
#ifdef __ANDROID__
    {F_GETLK64, "F_GETLK64"},       {F_SETLK64, "F_SETLK64"},
    {F_SETLKW64, "F_SETLKW64"},
#else
    {F_OFD_SETLK, "F_OFD_SETLK"},   {F_OFD_SETLKW, "F_OFD_SETLKW"},
    {F_OFD_GETLK, "F_OFD_GETLK"},
#endif
    {F_GETOWN_EX, "F_GETOWN_EX"},   {F_SETOWN_EX, "F_SETOWN_EX"}};

static const IntStrPair IOCTL_REQUESTS[] = {
    {FIONREAD, "FIOONREAD"},
    // <include/asm-i386/socket.h>
    {FIOSETOWN, "FIOSETOWN"},
    {SIOCSPGRP, "SIOCSPGRP"},
    {FIOGETOWN, "FIOGETOWN"},
    {SIOCGPGRP, "SIOCGPGRP"},
    //    {SIOCATMAR, "SIOCATMAR"},
    {SIOCGSTAMP, "SIOCGSTAMP"},

    // <include/asm-i386/termios.h>
    {TCGETS, "TCGETS"},
    {TCSETS, "TCSETS"},
    {TCSETSW, "TCSETSW"},
    {TCSETSF, "TCSETSF"},
    {TCGETA, "TCGETA"},
    {TCSETA, "TCSETA"},
    {TCSETAW, "TCSETAW"},
    {TCSETAF, "TCSETAF"},
    {TCSBRK, "TCSBRK"},
    {TCXONC, "TCXONC"},
    {TCFLSH, "TCFLSH"},
    {TIOCEXCL, "TIOCEXCL"},
    {TIOCNXCL, "TIOCNXCL"},
    {TIOCSCTTY, "TIOCSCTTY"},
    {TIOCGPGRP, "TIOCGPGRP"},
    {TIOCSPGRP, "TIOCSPGRP"},
    {TIOCOUTQ, "TIOCOUTQ"},
    {TIOCSTI, "TIOCSTI"},
    {TIOCGWINSZ, "TIOCGWINSZ"},
    {TIOCSWINSZ, "TIOCSWINSZ"},
    {TIOCMGET, "TIOCMGET"},
    {TIOCMBIS, "TIOCMBIS"},
    {TIOCMBIC, "TIOCMBIC"},
    {TIOCMSET, "TIOCMSET"},
    {TIOCGSOFTCAR, "TIOCGSOFTCAR"},
    {TIOCSSOFTCAR, "TIOCSSOFTCAR"},
    {FIONREAD, "FIONREAD"},
    {TIOCINQ, "TIOCINQ"},
    {TIOCLINUX, "TIOCLINUX"},
    {TIOCCONS, "TIOCCONS"},
    {TIOCGSERIAL, "TIOCGSERIAL"},
    {TIOCSSERIAL, "TIOCSSERIAL"},
    {TIOCPKT, "TIOCPKT"},
    {FIONBIO, "FIONBIO"},
    {TIOCNOTTY, "TIOCNOTTY"},
    {TIOCSETD, "TIOCSETD"},
    {TIOCGETD, "TIOCGETD"},
    {TCSBRKP, "TCSBRKP"},
    // {TIOCTTYGSTRUCT, "TIOCTTYGSTRUCT"},
    {FIONCLEX, "FIONCLEX"},
    {FIOCLEX, "FIOCLEX"},
    {FIOASYNC, "FIOASYNC"},
    {TIOCSERCONFIG, "TIOCSERCONFIG"},
    {TIOCSERGWILD, "TIOCSERGWILD"},
    {TIOCSERSWILD, "TIOCSERSWILD"},
    {TIOCGLCKTRMIOS, "TIOCGLCKTRMIOS"},
    {TIOCSLCKTRMIOS, "TIOCSLCKTRMIOS"},
    {TIOCSERGSTRUCT, "TIOCSERGSTRUCT"},
    {TIOCSERGETLSR, "TIOCSERGETLSR"},

    {TIOCSERGETMULTI, "TIOCSERGETMULTI"},
    {TIOCSERSETMULTI, "TIOCSERSETMULTI"},

    // <include/linux/ax25.h>
    {SIOCAX25GETUID, "SIOCAX25GETUID"},
    {SIOCAX25ADDUID, "SIOCAX25ADDUID"},
    {SIOCAX25DELUID, "SIOCAX25DELUID"},
    {SIOCAX25NOUID, "SIOCAX25NOUID"},
    //    {SIOCAX25DIGCTL, "SIOCAX25DIGCTL"},
    //    {SIOCAX25GETPARMS, "SIOCAX25GETPARMS"},
    //    {SIOCAX25SETPARMS, "SIOCAX25SETPARMS"},

    // <include/linux/,if_eql.h>
    {EQL_ENSLAVE, "EQL_ENSLAVE"},
    {EQL_EMANCIPATE, "EQL_EMANCIPATE"},
    {EQL_GETSLAVECFG, "EQL_GETSLAVECFG"},
    {EQL_SETSLAVECFG, "EQL_SETSLAVECFG"},
    {EQL_GETMASTRCFG, "EQL_GETMASTRCFG"},
    {EQL_SETMASTRCFG, "EQL_SETMASTRCFG"},

    // <include/linux/if_plip.h>
    {SIOCDEVPLIP, "SIOCDEVPLIP"},

    // <include/linux/if_ppp.h>
    /*
	{PPPIOCGFLAGS, "PPPIOCGFLAGS"},
	{PPPIOCSFLAGS, "PPPIOCSFLAGS"},
	{PPPIOCGASYNCMAP, "PPPIOCGASYNCMAP"},
	{PPPIOCSASYNCMAP, "PPPIOCSASYNCMAP"},
	{PPPIOCGUNIT, "PPPIOCGUNIT"},
	{PPPIOCSINPSIG, "PPPIOCSINPSIG"},
	{PPPIOCSDEBUG, "PPPIOCSDEBUG"},
	{PPPIOCGDEBUG, "PPPIOCGDEBUG"},
	{PPPIOCGSTAT, "PPPIOCGSTAT"},
	{PPPIOCGTIME, "PPPIOCGTIME"},
	{PPPIOCGXASYNCMAP, "PPPIOCGXASYNCMAP"},
	{PPPIOCSXASYNCMAP, "PPPIOCSXASYNCMAP"},
	{PPPIOCSMRU, "PPPIOCSMRU"},
	{PPPIOCRASYNCMAP, "PPPIOCRASYNCMAP"},
	{PPPIOCSMAXCID, "PPPIOCSMAXCID"},
    */
    // <include/linux/ipx.h>
    {SIOCAIPXITFCRT, "SIOCAIPXITFCRT"},
    {SIOCAIPXPRISLT, "SIOCAIPXPRISLT"},
    {SIOCIPXCFGDATA, "SIOCIPXCFGDATA"},

    // <include/linux/mroute.h>
    {SIOCGETVIFCNT, "SIOCGETVIFCNT"},
    {SIOCGETSGCNT, "SIOCGETSGCNT"},

    // <include/uapi/linux/wireless.h>
    {SIOCSIWCOMMIT, "SIOCSIWCOMMIT"},
    {SIOCGIWNAME, "SIOCGIWNAME"},
    {SIOCSIWNWID, "SIOCSIWNWID"},
    {SIOCGIWNWID, "SIOCGIWNWID"},
    {SIOCSIWFREQ, "SIOCSIWFREQ"},
    {SIOCGIWFREQ, "SIOCGIWFREQ"},
    {SIOCSIWMODE, "SIOCSIWMODE"},
    {SIOCGIWMODE, "SIOCGIWMODE"},
    {SIOCSIWSENS, "SIOCSIWSENS"},
    {SIOCGIWSENS, "SIOCGIWSENS"},
    {SIOCSIWRANGE, "SIOCSIWRANGE"},
    {SIOCGIWRANGE, "SIOCGIWRANGE"},
    {SIOCSIWPRIV, "SIOCSIWPRIV"},
    {SIOCGIWPRIV, "SIOCGIWPRIV"},
    {SIOCSIWSTATS, "SIOCSIWSTATS"},
    {SIOCGIWSTATS, "SIOCGIWSTATS"},
    {SIOCSIWSPY, "SIOCSIWSPY"},
    {SIOCGIWSPY, "SIOCGIWSPY"},
    {SIOCSIWTHRSPY, "SIOCSIWTHRSPY"},
    {SIOCGIWTHRSPY, "SIOCGIWTHRSPY"},
    {SIOCSIWAP, "SIOCSIWAP"},
    {SIOCGIWAP, "SIOCGIWAP"},
    {SIOCGIWAPLIST, "SIOCGIWAPLIST"},
    {SIOCSIWSCAN, "SIOCSIWSCAN"},
    {SIOCGIWSCAN, "SIOCGIWSCAN"},
    {SIOCSIWESSID, "SIOCSIWESSID"},
    {SIOCGIWESSID, "SIOCGIWESSID"},
    {SIOCSIWNICKN, "SIOCSIWNICKN"},
    {SIOCGIWNICKN, "SIOCGIWNICKN"},
    {SIOCSIWRATE, "SIOCSIWRATE"},
    {SIOCGIWRATE, "SIOCGIWRATE"},
    {SIOCSIWRTS, "SIOCSIWRTS"},
    {SIOCGIWRTS, "SIOCGIWRTS"},
    {SIOCSIWFRAG, "SIOCSIWFRAG"},
    {SIOCGIWFRAG, "SIOCGIWFRAG"},
    {SIOCSIWTXPOW, "SIOCSIWTXPOW"},
    {SIOCGIWTXPOW, "SIOCGIWTXPOW"},
    {SIOCSIWRETRY, "SIOCSIWRETRY"},
    {SIOCGIWRETRY, "SIOCGIWRETRY"},
    {SIOCSIWENCODE, "SIOCSIWENCODE"},
    {SIOCGIWENCODE, "SIOCGIWENCODE"},
    {SIOCSIWPOWER, "SIOCSIWPOWER"},
    {SIOCGIWPOWER, "SIOCGIWPOWER"},
    {SIOCSIWGENIE, "SIOCSIWGENIE"},
    {SIOCGIWGENIE, "SIOCGIWGENIE"},
    {SIOCSIWMLME, "SIOCSIWMLME"},
    {SIOCSIWAUTH, "SIOCSIWAUTH"},
    {SIOCGIWAUTH, "SIOCGIWAUTH"},
    {SIOCSIWENCODEEXT, "SIOCSIWENCODEEXT"},
    {SIOCGIWENCODEEXT, "SIOCGIWENCODEEXT"},
    {SIOCSIWPMKSA, "SIOCSIWPMKSA"},

    // <include/uapi/linux/sockios.h> see netdevice(7)
    {SIOCADDRT, "SIOCADDRT"},
    {SIOCDELRT, "SIOCDELRT"},
    {SIOCGIFNAME, "SIOCGIFNAME"},
    {SIOCSIFLINK, "SIOCSIFLINK"},
    {SIOCGIFCONF, "SIOCGIFCONF"},
    {SIOCGIFFLAGS, "SIOCGIFFLAGS"},
    {SIOCSIFFLAGS, "SIOCSIFFLAGS"},
    {SIOCGIFADDR, "SIOCGIFADDR"},
    {SIOCSIFADDR, "SIOCSIFADDR"},
    {SIOCGIFDSTADDR, "SIOCGIFDSTADDR"},
    {SIOCSIFDSTADDR, "SIOCSIFDSTADDR"},
    {SIOCGIFBRDADDR, "SIOCGIFBRDADDR"},
    {SIOCSIFBRDADDR, "SIOCSIFBRDADDR"},
    {SIOCGIFNETMASK, "SIOCGIFNETMASK"},
    {SIOCSIFNETMASK, "SIOCSIFNETMASK"},
    {SIOCGIFMETRIC, "SIOCGIFMETRIC"},
    {SIOCSIFMETRIC, "SIOCSIFMETRIC"},
    {SIOCGIFMEM, "SIOCGIFMEM"},
    {SIOCSIFMEM, "SIOCSIFMEM"},
    {SIOCGIFMTU, "SIOCGIFMTU"},
    {SIOCSIFMTU, "SIOCSIFMTU"},
    //  {OLD_SIOCGIFHWADDR, "OLD_SIOCGIFHWADDR"},
    {SIOCSIFHWADDR, "SIOCSIFHWADDR"},
    {SIOCGIFENCAP, "SIOCGIFENCAP"},
    {SIOCSIFENCAP, "SIOCSIFENCAP"},
    {SIOCGIFHWADDR, "SIOCGIFHWADDR"},
    {SIOCGIFSLAVE, "SIOCGIFSLAVE"},
    {SIOCSIFSLAVE, "SIOCSIFSLAVE"},
    {SIOCADDMULTI, "SIOCADDMULTI"},
    {SIOCDELMULTI, "SIOCDELMULTI"},
    // {SIOCADDRTOLD, "SIOCADDRTOLD"},
    //  {SIOCDELRTOLD, "SIOCDELRTOLD"},
    {SIOCDARP, "SIOCDARP"},
    {SIOCGARP, "SIOCGARP"},
    {SIOCSARP, "SIOCSARP"},
    {SIOCDRARP, "SIOCDRARP"},
    {SIOCGRARP, "SIOCGRARP"},
    {SIOCSRARP, "SIOCSRARP"},
    {SIOCGIFMAP, "SIOCGIFMAP"},
    {SIOCSIFMAP, "SIOCSIFMAP"}};

#endif
