#!/usr/bin/env bash
set -o nounset
# set -o xtrace

# Verify number of arguments
if [[ $# -ne 1 ]]; then
        echo "$0: missing package argument."
        exit 1
fi

package=$(./get_package $1)
echo "$0: removing traces for: '${package}'..."

adb shell su -c rm -rf /data/data/${package}/tcpsnitch
echo "$0: done!"
