#!/usr/bin/env bash
set -o nounset
# set -o xtrace
set -e

# Verify number of arguments
if [[ $# -ne 1 ]]; then
        echo "$0: missing package argument."
        exit 1
fi

# Get package name
exec 3>&2
package=$(./get_package $1 2>&3)

adb shell su -c am force-stop ${package}

./pull_traces ${package}
./quicklook

